name: run tests

on:
  push:
    branches-ignore:
      - main
        master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: set up python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    #run python script that checks if all issues have test contracts 
    - name: test contracts existence check
      run: python3 util/checkFilenames.py
    
    - name: set up node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: npm

    #install dependencies in the lock.json file
    - name: Install dependencies and build
      run: npm ci

    - name: Run tests
      run: npm test
